language: node_js
node_js:
  - "8"
os:
  - linux

sudo: required

services:
  - docker

cache:
  yarn: true

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t antoineaumjaud/api-shopping-list:latest .;
    docker push antoineaumjaud/api-shopping-list;
    fi

notifications:
  email: 
    on_failure: always
    on_sucess: never
  webhooks:
    urls:
      - https://api-synology-chatbot.aumjaud.fr/send-travis/continuous-integration
    on_success: always
    on_failure: always
